---
title: "dataWorkspace"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(tidyverse)
library(knitr)
library(readr)
library(party)
library(modelr)
library(xgboost)
```


```{r}
df <- read_csv("./data/combined-pre.csv") %>% select(Div, Date, HomeTeam, AwayTeam, FTHG, FTAG, FTR, HTHG, HTAG, HTR, HS, AS, HST, AST, HF, AF, HY, AY, HR, AR, B365H, B365D, B365A)

# need to bring in 2019-2020, 2020-2021, and 2021-2022 data in sperately bc they did not combine correctly

df1 <- read_csv("./data/2019-2020.csv") %>% select(Div, Date, HomeTeam, AwayTeam, FTHG, FTAG, FTR, HTHG, HTAG, HTR, HS, AS, HST, AST, HF, AF, HY, AY, HR, AR, B365H, B365D, B365A)

df2 <- read_csv("./data/2020-2021.csv") %>% select(Div, Date, HomeTeam, AwayTeam, FTHG, FTAG, FTR, HTHG, HTAG, HTR, HS, AS, HST, AST, HF, AF, HY, AY, HR, AR, B365H, B365D, B365A)

df3 <- read_csv("./data/2021-2022.csv") %>% select(Div, Date, HomeTeam, AwayTeam, FTHG, FTAG, FTR, HTHG, HTAG, HTR, HS, AS, HST, AST, HF, AF, HY, AY, HR, AR, B365H, B365D, B365A)

# La Liga match ups from the 2008-2009 season up until the 2021-2022 season
df <- rbind(df, df1, df2, df3)
```

## La Liga data
```{r}
# 08/09 season to 21/22 
classico <- df %>% filter(HomeTeam=="Real Madrid" & AwayTeam=="Barcelona" | AwayTeam=="Real Madrid" & HomeTeam=="Barcelona")

write_csv(classico, "./data/classico.csv")

classico_new <- read_csv("./data/Copy_of_classico.csv")
classico_for_xgb <- classico_new %>% select(-Date, -Div, -FTHG, -FTAG)
classico_no_chars <- classico_new %>% select(-Date, -Div, -FTHG, -FTAG)
```

```{r}
dim(classico_new)
classico_no_chars[,] <- lapply(classico_no_chars[,], as.factor)
```

```{r}
set.seed(100) #seed for reproducibility
index <- round(nrow(classico_no_chars) * 0.25, digits=0)
test_indices <- sample(1:nrow(classico_no_chars), index)
train_set <- classico_no_chars[-test_indices,] #80% training set
test_set <- classico_no_chars[test_indices,]  #20% test set

set.seed(100)
index_xgb <- round(nrow(classico_for_xgb) * 0.25, digits=0)
test_indices_xgb <- sample(1:nrow(classico_for_xgb), index)
train_set_xgb <- classico_for_xgb[-test_indices_xgb,] #80% training set
test_set_xgb <- classico_for_xgb[test_indices_xgb,]  #20% test set
```


```{r}
train_set
test_set

train_set_xgb
test_set_xgb
```